### PR TITLE
Add `.node` extension to native module require

### PR DESCRIPTION
**Pull request by floriansimon1**
So that the import works everywhere

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]
Thanks!

**Comment by floriansimon1** [comment]
If it makes sense, would it be possible for you to create another release so that I could rely on the original Semafour package instead of our fork?

Thanks in advance!

**Comment by cjihrig** [comment]
I just published v0.3.1. Just out of curiosity, where did the previous code not work? Node's `require()` should work automatically with `.js`, `.json`, and `.node` extensions.

**Comment by floriansimon1** [comment]
Thanks!

I had a problem with Typescript where it would complain that the included
file did not exist.

Le mer. 2 janv. 2019 à 09:17, Colin Ihrig <notifications@github.com> a
écrit :

**Comment by cjihrig** [comment]
Ah ok. I've never tried TypeScript with a native addon before, so I'll take your word for it 😄

**Comment by floriansimon1** [comment]
It could have been PEBKAC on my end TBH, but the fact that this alone solved my issue and it doesn't not cause any kind of bug kind of justifies merging the pull request IMO.

I would definitely have understood it if you had refused to merged it, but I'm grateful that you did! 

Thanks a lot!

**Pull request merged**
